services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
      # Montamos a pasta /app/data para o volume persistente
      - backend_data:/app/data
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  backend_data:
